timezone: Asia/Calcutta
permalink: :title

markdown: kramdown

author:
  name: Vaibhav Kanwal
  email: vaibhav.kanwal@gmail.com

# Custom URL Git Repo URL
baseurl: ''
url: http://vaibhavkanwal.com

# Localhost Repo URL
# baseurl: ''
# url: http://localhost:4000