timezone: Canada/Montreal
permalink: :title

markdown: kramdown

author:
  name: Karanvir Sawhney
  email: Kvss1992@gmail.com

# Custom URL Git Repo URL
baseurl: ''
url: http://kvss1992.github.io/

# Localhost Repo URL
# baseurl: ''
# url: http://localhost:4000